Appraising Binary Classification Models
======================================
Interesting Theory Stuff : Accuracy, Precision, F-Measures, Recall, Specificity, Sensitivity


### Set up some data

In [20]:
import numpy as np

y_pred = np.zeros(10000)
y_test = np.zeros(10000)

indices1  = np.random.randint(0,10000,300)
indices2  = np.random.randint(0,10000,400)
indices3  = np.random.randint(0,10000,500)
y_pred[indices1] = 1
y_test[indices2] = 1
y_pred[indices3] = 1
y_test[indices3] = 1


In [21]:
np.sum(y_test)

858.0

In [22]:
np.sum(y_pred)

774.0

In [23]:
from sklearn.metrics import accuracy_score
print('Accuracy score: ', accuracy_score(y_test, y_pred))  


Accuracy score:  0.939


In [24]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

array([[8879,  263],
       [ 347,  511]])

In [11]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

        0.0       0.96      0.97      0.97      9137
        1.0       0.65      0.58      0.62       863

avg / total       0.93      0.94      0.94     10000



In [12]:
from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_pred)

In [13]:
precision

array([ 0.0863    ,  0.65116279,  1.        ])

In [14]:
recall

array([ 1.        ,  0.58400927,  0.        ])

In [15]:
thresholds

array([ 0.,  1.])