

<h1>Random Number Generation with NumPy</h1>

 For the sake of brevity, the specific functions names are given in the example below, rather than the full specification.

The <tt>rand()</tt> command is fully specified as <tt>np.random.rand()</tt>



### Core Random Number Generators
NumPy random number generators are all stored in the module <tt>numpy.random</tt>. 
These can be imported with using <tt>import numpy as np</tt> and then calling <tt>np.random.rand</tt>.

<h4><tt>rand</tt>, <tt>random_sample</tt></h4>
<tt>rand</tt> and <tt>random_sample</tt> are uniform random number generators whichare
 identicalexceptthat rand takes a variable number 
of integer inputs – one for each dimension – while <tt>random_sample</tt> takes a n-element tuple. 


In [2]:
from numpy import random

 <tt>random_sample</tt> is the preferred NumPy function, and <tt>rand</tt> is a convenience function primarily for 
MATLAB users.


In [7]:

x = random.rand(2,3,4) 
y = random.random_sample((3,4,5))
print(x)

[[[ 0.0955836   0.03376582  0.38817283  0.85912198]
  [ 0.04482029  0.10219086  0.89684468  0.54820184]
  [ 0.15114895  0.6866938   0.73250885  0.75220145]]

 [[ 0.34889475  0.73198403  0.28772946  0.10666828]
  [ 0.17649262  0.32695649  0.51585941  0.78629993]
  [ 0.78252941  0.12911372  0.10055781  0.61494607]]]



<br>
<h4><tt>randn, standard_normal</h4>
<ul>
<li> <tt>randn</tt> and <tt>standard_normal</tt> are standard normal (i.e. Z-value) random number generators. <tt>randn</tt>, like <tt>rand</tt>, takes a
variable number of integer inputs, and <tt>standard_normal</tt> takes an n-element tuple. 
<li> Both can be called
with no arguments to generate a single standard normal (e.g. randn()). 
<li> <tt>standard_normal</tt> is the preferred
NumPy function, and <tt>randn</tt> is a convenience function intended primarily for MATLAB users .
</ul>


In [6]:
x = random.randn(3,4,5)
y = random.standard_normal((3,4,5))
print(x)

[[[-0.29933325  1.59225056  0.4002575   0.55517836  0.11246419]
  [-0.32775563 -0.17327254  0.63177113  1.03844333 -0.62764267]
  [ 0.98311952  0.3749228  -0.20881392 -0.62546328  0.09324813]
  [-0.42731764  0.0780507  -0.31227948  0.09510427  0.31145272]]

 [[-0.27788454  0.69382967 -0.01061293  0.60195604 -0.24112627]
  [ 0.66711036  0.37401446 -1.4340408  -1.33130408  0.59943552]
  [ 0.01088137 -0.74842078  0.22271366 -0.61713332 -1.29931144]
  [ 0.4655614   0.39209554  1.45063744 -0.47540715  1.78263688]]

 [[ 1.90659355  0.36309475  1.55772701  1.71017227  0.515373  ]
  [ 0.30507215  0.10262419 -1.88907061 -1.24840471 -0.04699204]
  [-0.3347669   0.52992483 -1.08687925  1.41647664 -0.80305374]
  [ 0.79514637  0.44449097 -1.16431231  0.17817714  0.93697488]]]



<h4><tt>randint, random_integers</h4>
<tt>randint</tt> and <tt>random_integers</tt> are uniform integer random number generators which take 3 inputs: low,
high and size. 
<ul>
<li> <tt>low</tt> is the lower bound of the integers generated, 
<li> <tt>high</tt> is the upper,
<li> <tt>size</tt> is a n-elementtuple. 
</ul>


<b>Important:</b><br>
<tt>randint()</tt> and <tt>random_integers</tt> differ in that <tt>randint</tt> generates integers exclusive of the value in <tt>high</tt>
(as do most Python functions), while <tt>random_integers</tt> includes the value in <tt>high</ttt> in its range.


In [28]:
x = random.randint(0,10,(100))
x.max() 
# Is 9 since range is [0,10)

9

In [27]:
y = random.randint(0,10,(100))
y.max() 
# Is 10 since range is [0,10]

9


<h3> Random Array Functions</h3>
<br>
<h4><tt>shuffle</h4>
<tt>shuffle</tt> randomly reorders the elements of an array in place.

In [35]:
x = [1,2,3,4,5,6,7,8,9,10,11,12]
random.shuffle(x)

In [36]:
x

[1, 2, 12, 5, 4, 3, 11, 8, 7, 6, 9, 10]

<h4><tt>permutation</h4>
<tt>permutation</tt> returns randomly reordered elements of an array as a copy while not directly changing the
input.

In [38]:
x = [1,2,3,4,5,6,7,8,9,10,11,12]
random.permutation(x)



array([10,  2,  1,  4,  8,  5,  7, 11,  6,  3,  9, 12])

In [39]:
x


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

<h3>Select Random Number Generators</h3>
<ul>
<li> NumPy provides a large selection of random number generators for specific distribution. 
<li> All take between
0 and 2 required inputs which are parameters of the distribution, plus a tuple containing the size of the
output. 
<li> All random number generators are in the module <tt>numpy.random}.
</ul>
<br>


<h4><tt>seed</h4>

<ul>
<li> <tt>numpy.random.seed</tt> is a more useful function for initializing the random number generator, and can be
used in one of two ways. <tt>seed()</tt> will initialize (or reinitialize) the random number generator using some
actual random data provided by the operating system.

<li> <tt>seed( s )</tt> takes a vector of values (can be scalar) to
initialize the random number generator at particular state. 
<li> <tt>seed( s )</tt> is particularly useful for producing
simulation studies which are reproducible. 
<h4>Example</h4>
In the following example, calls to <tt>seed()</tt> produce different
random numbers, since these reinitialize using random data from the computer, while calls to <tt>seed(0)</tt>
produce the same random number or sequence of random numbers.
<br>
</ul>

In [42]:
random.seed()
random.randn()

-0.3179158260717359

In [43]:
random.seed()
random.randn()

-0.7547207538762433

In [44]:
random.seed(0)
random.randn()

1.764052345967664

In [45]:
random.seed(0)
random.randn()

1.764052345967664


NumPy always calls <tt>seed()</tt>  when the first random number is generated. As a result. calling <tt>standard_normal()</tt>
across two “fresh” sessions will not produce the same random number.
<br>

### Random Array Functions


<h4>Select Random Number Generators</h4>
<ul>
<li> NumPy provides a large selection of random number generators for specific distribution. 

<li> All take between 0 and 2 required inputs which are parameters of the distribution, plus a tuple containing the size of the output. 
<li> All random number generators are in the module 
<tt>numpy.random</tt>.
</ul>


<h4>Bernoulli</h4>
<ul>
<li> There is no ***Bernoulli generator***. 
<li> Instead use <tt>binomial(1,p)</tt> to generate a single draw or <tt>binomial(1,p,(10,10))</tt> to generate an array where 
<tt>p</tt>is the probability of success.
</ul>

<h4>Simulation and Random Number Generation</h4>
<ul>
<li> Computer simulated random numbers are usually constructed from very complex but ultimately deterministic
functions. 
<li> Because they are not actually random, simulated random numbers are generally described
to as **pseudo-random**. 
<li> All pseudo-random numbers in NumPy use one core random number generator
based on the ***Mersenne Twister***, a generator which can produce a very long series of pseudo-random
data before repeating (up to $2^{19937} - 1$ non-repeating values).
</ul>


<h4><tt>RandomState</h4>
<tt>RandomState</tt> is the class used to control the random number generators. Multiple generators can be initialized
by <tt>RandomState</tt>.


In [21]:
gen1 = random.RandomState()
gen2 = random.RandomState()

# Generate a uniform
gen1.uniform() 

0.053348148799395756

In [22]:
state1 = gen1.get_state()
gen1.uniform()

0.9959202678511813

In [23]:
# Different, since gen2 has different seed
gen2.uniform()

0.227249825617046

In [24]:


# Same uniform as gen1 after assigning state
gen2.set_state(state1)
gen2.uniform() 


0.9959202678511813


<h4><tt> State</tt></h4>
<ul>
<li> Pseudo-random number generators track a set of values known as the \textit{state}. 
<li> The state is usually a vector
which has the property that if two instances of the same pseudo-random number generator have the
same state, the sequence of pseudo-random numbers generated will be identical. 
<li> The state of the default
random number generator can be read using <tt>numpy.random.get_state</tt> and can be restored using
<tt>numpy.random.set_state</tt>.
</ul>


In [25]:
st = random.get_state()
#print(st)
print(random.randn(4))

random.set_state(st)
print(random.randn(4))


[ 0.11107481  0.09273262 -1.00267879  0.46292336]
[ 0.11107481  0.09273262 -1.00267879  0.46292336]




<ul>
<li> The two sequences are identical since they the state is the same when <tt>randn</tt> is called. 
<li> The state is a 5-
element tuple where the second element is a 625 by 1 vector of unsigned 32-bit integers. 
<li> In practice the
state should only be stored using <tt>get_state</tt> and restored using <tt>set_state</tt>.
</ul>

<br>




<h4><tt>get_state</h4>

<ul>
<li> <tt>get_state()</tt> gets the current state of the random number generator, which is a 5-element tuple. 
<li> It can be
called as a function, in which case it gets the state of the default random number generator, or as a method
on a particular instance of <tt>RandomState</tt>.
</ul>

<h4><tt>set_state</h4>

<ul>
<li> <tt>set_state(state)</tt> sets the state of the random number generator. 
<li> It can be called as a function, in which
case it sets the state of the default random number generator, or as a method on a particular instance of
<tt>RandomState</tt>.<li> <tt>set_state</tt> should generally only be called using a state tuple returned by <tt>get_state</tt>.
</ul>